### ISSUE TITLE
サークル予定地に寂れた荒野の画像をつける

### ISSUE THREAD

**Issue by himanoa** [Okimoti/tasks#1]
俺たちがマッドマックス!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by potato4d** [comment]
わざわざ寂れた荒野の画像をフリー素材で公開したがる人間はいないことがわかったので適当に終わってそうな画像にした

![screen shot 2018-02-03 at 0 07 44](https://user-images.githubusercontent.com/6993514/35739861-59d15698-0876-11e8-9efe-2aa5f13507f3.png)
