### ISSUE TITLE
BOOTHの売り上げ分配を考える

### ISSUE THREAD

**Issue by himanoa** [Okimoti/tasks#20]
コミケ後までPending

**Comment by potato4d** [comment]
いくつかのパターンを考えてみた。

## 1. そもそも売らない

売らないので終わり。

## 2. 誰か代表者が販売権を買い取り、その後の売上は全て代表者のものとする

- 面倒でないパターン

## 3. 誰か代表者が販売権を買い取り、3 ヶ月ほどは折半とするが、その後の売上は全て代表者のものとする

- 少し面倒なパターン
- おそらく全体で一番収益がブレない

**Comment by potato4d** [comment]
多分折半になりそう、別でbooth Issueを建てる
