### ISSUE TITLE
巻末のプロフページの情報を書くIssue

### ISSUE THREAD

**Issue by potato4d** [Okimoti/tasks#21]
1. 名前
2. メッセージ(120文字以内ぐらいで)
3. リンク(Twitterでも個人サイトでも)
4. アイコン画像のURL

を書いてほしい

**Comment by potato4d** [comment]
@nametaketakewo

**Comment by himanoa** [comment]
1. ひまのあ
2. 生放送追いかけてたら睡眠時間が破壊されて出社時間も壞れた。来世は酒になりたい
3. https://himanoa.net
4. https://avatars0.githubusercontent.com/u/18651963?s=88&v=4

**Comment by masaakikunsan** [comment]
1. まさあきくんさん
2. 最近はもうプログラミングせずに隠居したいと思ってます。フロントばっかやってるので最近はもうフロントやりたくない...来世は犬になってご主人様に尽くしたい
3. https://masaakikunsan.com
4. https://img.esa.io/uploads/production/attachments/9167/2018/07/15/32742/85466687-ee19-413b-84a1-60d893e85acb.jpg

**Comment by nametaketakewo** [comment]
1. なめたけ
1. 所謂学生エンジニアです。普段はRubyやPythonやGoでバックエンド開発をしています。最近はReact.jsでフロントエンド開発とかもやっています。うっかりミスで親の扶養から外れてしまい泣きながらフリーランスもどきになりました。
1. https://nametaketakewo.net
1. https://pbs.twimg.com/profile_images/978696853146316800/uIa33Jlt_400x400.jpg

**Comment by potato4d** [comment]
集まったのでクローズ。こっちでよしなに整えます
