### ISSUE TITLE
pixivPAY の準備をする

### ISSUE THREAD

**Issue by potato4d** [Okimoti/tasks#24]
- @himanoa のアカウントをマスタにする（会計口座が大体今ひまのあに収束しているので）
- 当日オペおよびアシスタントモードは @potato4d が知見を持っているので当日やる

**Comment by himanoa** [comment]
🙆

**Comment by himanoa** [comment]
ちょっと帰ったら弄ってみるわ

**Comment by potato4d** [comment]
やったらしい
