### ISSUE TITLE
20180128_誕生日_議事録

### ISSUE THREAD

**Issue by himanoa** [Okimoti/tasks#5]
# 決めること

- サークル名
- 申し込み期日までのロードマップ引き
- サークルカット決め
- 何について書くか(about)
- 記述とCIどうするか
- 本をどうするか
- メアドとか
- 定例頻度

# 決め

## 記述とCIどうするか

markdownでみんなでワイワイして、https://writing.viola.pub/ で調整
markdownでなんとかなればあとはどうにでもなるので確定。violaは知見が薄いのでやっていきはするが、さしかえも考える
pandocもありかもね

## サークルカット

文字だけでもとりあえずどうにかなりそう

## コンセプト決め

- Webについてかきたい(各位で考えてまとめよう)

## 本どうするかd

社会人金リソースがあるので贅沢にやろう

## メアドどうするか問題

個人メアドでやり続けてもいいけどSPOFになりがち
今回はとりあえず誤魔化して意識たかくなったらやる
今回の申し込みは @masaakikunsan 一任でいく

## 定例頻度

一週間に一度が望ましいが、人々の予定が合わないので各位の予定優先でやる

# 次回持ち越し(ばっくろぐ)

- コンセプトを煮詰める
- ロゴ
- 表紙の依頼先 #8
  - にともなって連絡が滞るのは悪いことなのでメアド取りたい
    - ドメイン
    - 払いかた
       - サークル売りあげからこう… 
    - メール鯖
- 印刷所
- ロードマップ決め

**Comment by masaakikunsan** [comment]
・サークルカットのサイズは縦903ドット×635ドット固定です。(600dpi固定で出力します)
・トーンを使う絵柄については、白黒2値のカットを推奨します
・サークルドットエムエスのサイトにてオンライン申込開始前から、AdobePhotoShop形式等でのサークルカットのテンプレートを提供しています（→サークルドットエムエスのテンプレートページ）
・対応する画像フォーマットは以下の通りです
PNG
GIF
BMP
JPEG

**Comment by himanoa** [comment]
次回 土曜
