### ISSUE TITLE
表紙依頼先

### ISSUE THREAD

**Issue by masaakikunsan** [Okimoti/tasks#8]
表紙の依頼先を決める
推しをコメントに書いてくれ(絵も含めて)

**Comment by masaakikunsan** [comment]
@smimimi06 鍵垢ですまそ
高校の頃から仲の良いネ友です
いろんなタイプの絵かけて結構好きです
![unnamed 2](https://user-images.githubusercontent.com/24547663/35473517-1090dee6-03c5-11e8-8ba0-6e58076bff42.jpg)
![unnamed 1](https://user-images.githubusercontent.com/24547663/35473518-10c174ca-03c5-11e8-97ff-092af256049f.jpg)
![unnamed](https://user-images.githubusercontent.com/24547663/35473519-10e7215c-03c5-11e8-8684-84bed282f443.jpg)

**Comment by himanoa** [comment]
Name: [@tama0104](https://twitter.com/tama0104)
Pixiv: https://www.pixiv.net/member.php?id=3038880

懸念点ありで多分他の技術サークルの依頼も受けてるかもしれず

**Comment by masaakikunsan** [comment]
え。たまさん好きになってしまった

**Comment by himanoa** [comment]
たま。さん…いいよね…

**Comment by masaakikunsan** [comment]
Name: @misaki_cradle
http://cradle.cc/about.html

おいくら万円詰んだら書いてくれるのでしょうか....
